### ISSUE TITLE
Empty grouping labels should provide a fallback

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/Hierarchy#2]
I was testing to see what would happen if I left a number of the label fields empty, and the result is that a grouping can appear with a blank title in both the Hierarchy block and the main heading in the public view. I would expect the fallback to be the item set name, or "[Untitled]".

Here's the setup within Hierarchy.
<img width="565" alt="image" src="https://github.com/user-attachments/assets/3d444216-4a5f-4ffe-864f-91c7420dd581">
 
Here's the grouping with an empty title.
<img width="387" alt="image" src="https://github.com/user-attachments/assets/1c71f21e-10a3-429e-80fa-535e03d3208c">

Here's the empty title in the public view.
<img width="396" alt="image" src="https://github.com/user-attachments/assets/4fc09815-8f2a-4d2b-aef0-e177262c346c">

(#1)

**Comment by matthewjmckinley** [comment]
You're right, that could be more elegant. A Hierarchy can't really fall back on an item set, since those are assigned at the Grouping level under the Hierarchy, but I can have them show as [untitled] when nothing is there.

**Comment by matthewjmckinley** [comment]
Fixed in https://github.com/omeka-s-modules/Hierarchy/commit/aa552652f4d468c2eb42f8c1273a5c705eb974fd
